### ISSUE TITLE
tabular data/new datasets

### ISSUE THREAD

**Issue by nazaretl** [thulas/dac-label-noise#10]
Hi,
thanks for sharing your implementation. I have two questions about it:

1.	Does it also work on tabular data?
2.	Is the code tailored to the datasets used in the paper or can one apply it to any data?

Thanks!

**Comment by thulas** [comment]
Yes, in theory, you should be able to apply it to tabular and other types of data. The only real requirements are that the task at hand is classification and that you have a fully labeled dataset (which may or may not have labeling errors).

For this code to work with different datasets, you will have to modify some of the input processing routines in the driver script, but the loss function and PID routines are independent of the data.

**Comment by nazaretl** [comment]
thanks for clarifying!
